### ISSUE TITLE
HEIC files cannot be previewed

### ISSUE THREAD

**Issue by RevBlood** [nemethviktor/GeoTagNinja#89] opened 2023-09-30 17:53 UTC
**Describe the bug**
Whenever a HEIC file is selected, the UI will show "Could not retrieve/generate image preview"

**To Reproduce**
1. Navigate to any folder containing a HEIC file
2. Click the HEIC file
3. Now the UI should show "Could not retrieve/generate image preview"

**Expected behavior**
An image preview should be shown

**Screenshots**
![Unavngivet](https://github.com/nemethviktor/GeoTagNinja/assets/3540099/68f6a6bc-f0d2-44bd-b0c0-2ef877ed9b95)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Language/Culture: da-DK
 - Full Path of Picture: C:\Users\treel\OneDrive\Kamerarulle\Annas billeder - HEIC\20230630_120919.heic

**Additional context**
None

**Comment by nemethviktor** [comment] 2023-09-30 21:06
Hey, thanks for the feedback. Indeed now that I have had a look at it exifTool doesn't support that particular image type. --> https://exiftool.org/forum/index.php?topic=12597.0#:~:text=There%20is%20no%20stand%2Dalone,heic%20container%20to%20be%20viewable. 

There is however another open-source C# library that does the job, I've patched that in.

Anyway, you're in for a treat (?) of sorts because I have done a bit of work recently on the app but not managed to test it out properly so you'll be the guinea pig I'm afraid (stuff should work tho') -- give it a whirl pls.
https://drive.google.com/open?id=18iI77SIdrIv-joOtyT0-MzqOVtB5OgM0&usp=drive_fs

**Comment by RevBlood** [comment] 2023-10-01 08:27
Wow, that was quick!

I tried the test cases I could come up with, based on the data that I have.
General observation is that the previews are a bit slow. Each time a preview is loaded, the UI hangs for a few seconds.
That said, the program is actually workable for my purpose now (And does something that GeoSetter couldn't). So thank you very much for this build. I will be using this going forward.

Anyways, for the tests, I tried out these things. Everything seems to work, save for the metadata editing feature, which consistantly throws an exception.

  *   OK: HEICs from Samsung Galaxy S21
  *   OK: HEICs from Samsung Galaxy S23
  *   OK: Spamming selection of files in the UI (UI locks on each selection until preview is loaded)
  *   OK: Multi-selecting images (UI shows the last image selected)
  *   OK: Select file -> File -> Copy all geodata -> Select other file -> Paste all geodata
  *   OK: Select file -> Click position on map -> Save current coordinates to selected file
  *   OK: Double click image -> Hit "Cancel"
  *   ERROR: Double click image -> Hit "Ok" -> Exception is thrown -> Select another image -> Select the first image again -> Same exception is thrown again. See below. (Per

Exception is in Danish and says that the value 56218508 is invalid for Value. Value must be between Minimum and Maximum.

System.ArgumentOutOfRangeException: Værdien '56218508' er ugyldig for 'Value'. 'Value' skal være mellem 'Minimum' og 'Maximum'.
Parameternavn: Value
   ved System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
   ved GeoTagNinja.FileListViewMapNavigation.ListViewItemClickNavigate()
   ved GeoTagNinja.FrmMainApp.<lvw_HandleSelectionChange>d__80.MoveNext()
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved GeoTagNinja.FrmMainApp.<lvw_FileList_MouseUp>d__84.MoveNext()
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

________________________________
Fra: Viktor Nemeth ***@***.***>
Sendt: 30. september 2023 23:07
Til: nemethviktor/GeoTagNinja ***@***.***>
Cc: Morten Møller Jakobsen ***@***.***>; Author ***@***.***>
Emne: Re: [nemethviktor/GeoTagNinja] HEIC files cannot be previewed (Issue #89)


Hey, thanks for the feedback. Indeed now that I have had a look at it exifTool doesn't support that particular image type. --> https://exiftool.org/forum/index.php?topic=12597.0#:~:text=There%20is%20no%20stand%2Dalone,heic%20container%20to%20be%20viewable<https://exiftool.org/forum/index.php?topic=12597.0#:~:text=There%20is%20no%20stand-alone,heic%20container%20to%20be%20viewable>.

There is however another open-source C# library that does the job, I've patched that in.

Anyway, you're in for a treat (?) of sorts because I have done a bit of work recently on the app but not managed to test it out properly so you'll be the guinea pig I'm afraid (stuff should work tho') -- give it a whirl pls.
https://drive.google.com/open?id=18iI77SIdrIv-joOtyT0-MzqOVtB5OgM0&usp=drive_fs

**Comment by nemethviktor** [comment] 2023-10-01 10:04
I'll have a look at the numeric formatting issue. The problem is that there are so many different "cultures" (ie. Windows's definition of how various countries format things like numbers) and while I have tested w/ Finnish [English], DK hasn't come up as an issue so far.
Alas I've found an unrelated bug already that will be fixed.
Re: HEIC generation being slow: yeah, not much I can do about it I'm afraid. HEIC doesn't have a preview built into it so it needs to be converted to JPG - the library used only allows to extract either the thumbnail (very small) or the whole image. Particularly if your files are big (in terms of megapixels), that will take a while.

**Comment by RevBlood** [comment] 2023-10-01 14:51
I found a set of old photos to work on today, coming off of an Apple iPhone 11.
So far, everything is working great for my purposes, but I did find another minor issue:
The HEIC preview does not take into account rotation, meaning images are sometimes lying down, or even upside down.
When displaying the same images in the built in Windows image viewer, the images are shown with the correct rotation.

None of this stops me from working on the images though.

**Comment by nemethviktor** [comment] 2023-10-01 15:22
That's normal - as in if you check other raw file previews they are also
the wrong orientation. I haven't managed to figure out how to get around it
but factually aware. Might ask the ai at some point, it's been useful for a
lot of coding stuff lately.

This message has been brought to you by my Honor Magic5 Pro and myself. Any
typos blame the phone.

**Comment by nemethviktor** [comment] 2023-10-01 20:10
![image](https://github.com/nemethviktor/GeoTagNinja/assets/58767235/10a13049-7e4c-49f2-a960-b555f313d54a)

Getting there....AI can do wonders. 
Also will be patching (already have, it's just not uploaded yet) the normal RAW/preview creation.
Will look at the numbers issue now.

**Comment by nemethviktor** [comment] 2023-10-01 21:24
Okay, try the link from before (updated).

**Closed** 2023-10-07 13:14 UTC
Labels: bug

**Comment by RevBlood** [comment] 2023-10-11 20:37
Hi there. Sorry for the late reply.

Tested again tonight, and the new release is a massive improvement.
Not only did you fix the rotation - Somehow, you also made the previews load MUCH faster.
This definitely eases the work of tagging each picture.

On the downside, the culture issue still persists. This is not a priority for me, but might be nice for you to know.

**Comment by nemethviktor** [comment] 2023-10-12 18:15
Hmmm I will have a second look at that, I thought I fixed it but maybe not
- apologies.


This message has been brought to you by my Honor Magic5 Pro and myself. Any
typos blame the phone.
