### ISSUE TITLE
Saving places for later retrieval

### ISSUE THREAD

**Issue by aphalo** [nemethviktor/GeoTagNinja#37] opened 2022-12-18 11:06 UTC
First of all: it is great to have a GeoSetter replacement!! I have been looking for something like GeoTagNinja for quite some time! Many thanks!

What I miss most is the ability to save locations (coordinates) for later reuse when manually geocoding images taken in places where I am consistly (home, work, etc.).

**Comment by pbranly** [comment] 2022-12-18 11:13
Hi
I am not sure to understand what you need 
On my side I use PixTrack in my Iphone whenever I want very accurate positions but is drains a bit the battery. The file goes to my Dropbox and so in my PC and I can import easily this file to the photos via GTN
And when I didn't use this program, I have positions from google in a json format 
It is less accurate but file is also compatible with GTN
Phil

**Comment by nemethviktor** [comment] 2022-12-18 11:16
Hi everyone

That's ok, I'll add it to the Todo list, probably in January
Phil - I know what he means. Naming places and using them as instant tag ;)

V

**Comment by aphalo** [comment] 2022-12-18 14:33
Yes, that's it. Many thanks!

**Comment by aphalo** [comment] 2022-12-18 22:59
@aphalo An idea: this could be implemented by adding the posibility of saving and retrieving the location metada for later reuse within the dialogue for editing the metadata that pops up on double clicking on the file data.

**Comment by nemethviktor** [comment] 2022-12-19 07:57
You mean save it into the file as a custom tag?

**Comment by aphalo** [comment] 2022-12-19 11:13
@nemethviktor I meant to save the coordinates (and possibly related metadata) to a text/json/xtml file with each location tagged with a user-supplied name, so that the locations can be later retrieved and applied to other photographs. Geocoding is usually applied to photographs taken outdoors, but it is also useful for indoor locations where there isn't good GPS reception or for places one visits repeatedly over a long time and one wants to geocode all images at a given location identically. Obviously, also when manually geocoding photographs taken even before GPS was invented. I find the "preset coordinates" very convenient when manually geocoding images as a way as focusing the map at a good starting location for manually seting the coordinates by clicking on the map.

**Comment by nemethviktor** [comment] 2022-12-19 11:57
I think what you'd like is easy to do but....(there's always a but).
- I am more for the idea of saving a local repo (by which I mean within the app) of say "Home" = (x,y) coords and that can be retrieved and stamped onto files. It's not difficult to do and makes good sense to me. 
- In particular the _keyword field_ is tricky: one smaller issue is that at the moment GTN isn't handling the keyword tag(s) and I'd need to look into that to reliably handle. The other is that I'm not sure what you'd like to do with it. (particularly the Keyword tag). Overriding coords/metadata from the local repo as per above isn't a problem, but do you just want to add an extra Keyword (say "home") or is there anything particular you'd like?

**Comment by nemethviktor** [comment] 2022-12-19 17:16
Basically all "permanent" (ie things that are retained between launches) stuff in GTN is stored in a local sqlite file - if you aren't familiar with it then imagine something like an Excel file of sorts. 
So storing things like "home" = coords(x,y), city(x) etc and recalling it quite simple. I have it half done now but not finished yet.

**Comment by nemethviktor** [comment] 2022-12-19 18:03
Apologies in advance if this might lead to confusion
I've copied (just now) an installer to the google drive link I shared earlier.
- this version _does not have the city/sublocation changes_ - it's a different commit and until there's an agreement on how to handle things i'd like to keep staged commits separately
- _this version has the "favourites" logic/request_

![image](https://user-images.githubusercontent.com/58767235/208490818-08f7a8c9-5a7c-45b4-8bdf-814779f9ddc9.png)

See if it's what you're after.

**Comment by nemethviktor** [comment] 2022-12-20 16:46
Update: I've moved this file to https://drive.google.com/file/d/1rCrxKbH5UR9E5QMX_vh_ZZKJmPDl2R8c/view?usp=share_link as a one-off because i need to overwrite the generic dev channel with something else.
@aphalo  can you have a look pls and comment if the logic used here is ok as i'd like to push a general release before Thursday. Thanks.

**Comment by aphalo** [comment] 2022-12-20 18:45
@nemethviktor 
Hi Viktor,
Thanks! I downloaded a couple of hours ago from the old link and now from this link, but I do not see this favourites field. Do I need to uninstall before installing the new version? I saw "Version: 0.7.8389 [20221220:1644]" in About. Uninstalled, intalled from the link above and get: Version: 0.7.8387 [20221218:2121]
However, I do not see the Favourites field and icons. Is the file in the link the wrong one? or is there additional file cleanup for me to do?

**Comment by nemethviktor** [comment] 2022-12-20 18:55
Hmmm let me check a little later, out and about now, should be back in 2-3 hours - will report back then.

**Comment by nemethviktor** [comment] 2022-12-20 21:04
@aphalo try the link again pls - should work now. You may need to uninstall a previous version.

**Comment by aphalo** [comment] 2022-12-20 21:53
@nemethviktor Yes, now I got the correct version. Seemed to work for a while but suddenly got:
![image](https://user-images.githubusercontent.com/2743159/208771065-6e44b717-9a93-49c5-b0ce-5706032d3881.png)
and had to close and restart GeoTagNinja as the message would pop back.

I think this was caused by accidentally saving data from an image that was not geoencoded. So, a check of valid data before saving as a favourite or when retrieving data would be useful. I have not been able to reproduce this problem yet, even by saving a favourite after using the dialogue to clear the GPS settings.

Each time I apply a favourite to an image the names of all saved favorites is added to the dropdown list. After closing and reopening GeoTagNinja the drop down list shows each favourite once, but then the problem repeats. Otherwise it seems to work as as expected.

**Comment by nemethviktor** [comment] 2022-12-20 22:16
> LongitudeRef

Ahh.. Gotcha. I _think_ it's fixed now (link same/below)

> Each time I apply a favourite to an image the names of ....

My bad, fixed. (file in the same link/location)

**Comment by aphalo** [comment] 2022-12-20 22:34
@nemethviktor 
Thanks!
Tried it, but out of multiple favourites the dropbox shows only one.

_LongitudeRef_ The problem was intermitent so will take some time to know for sure if it is solved.

**Comment by aphalo** [comment] 2022-12-20 22:36
It is past midnight here. I have meetings in the morning. I will be busy until about lunchtime.

**Comment by nemethviktor** [comment] 2022-12-20 22:52
I think it's a case of it's getting late here too - your observation re: one line only is correct and it's because I put a list.clear() in the wrong line. Should zzzz.

LongitudeRef -> I think the issue was how blanks are handled, which is a more overall problem across the app. The main grid shows a `-` character for blank strings but the exif tags that get written are just blank blanks. in this case i failed to account for that and we were trying to write a `-` for empty things (in your case LongitudeRef but possibly also others), which triggered an error.

Updated the link yet again, look at it whenever convenient.

**Comment by aphalo** [comment] 2022-12-20 23:44
Thanks! I quickly skimmed the IPTC standard, the IPTC Extenssion seems now preferred for location data. Reading between lines, it seems that sublocation is that level 5 when below a city but possibly at level 4 when outside a city. I guess, then that the correct behaviour is to leave the City field empty. 

https://iptc.org/std/photometadata/specification/IPTC-PhotoMetadata#location-structure
https://iptc.org/std/photometadata/specification/IPTC-PhotoMetadata#location-created
https://iptc.org/std/photometadata/specification/IPTC-PhotoMetadata#location-structure

The most informative is the third of the links, but I got there navigating the other two.

**Comment by nemethviktor** [comment] 2022-12-21 07:37
I'm assuming that last comment refers to the other topic ;)

**Comment by aphalo** [comment] 2022-12-21 08:05
Yes. ;-)

**Comment by nemethviktor** [comment] 2022-12-21 09:17
Cool - may I assume then this is good to go?

**Comment by aphalo** [comment] 2022-12-21 14:02
As I understand the standard, "Sublocation" is not part of a hierarchy, it is just a place name. Say in the middle of the ocean, there is no country, no city, etc, no administrative entity below Earth. But still the sublocation is the field to use for the name of the ocean. I think it is important to respect this standard as this will be what photo-editing programs and asset management programs expect, and doing things differently would make GeoTagNinja incompatible with them. I am clarifying this because I think my previous message was unclear.

**Comment by nemethviktor** [comment] 2022-12-21 14:13
Wrong thread ;)

**Closed** 2022-12-21 15:40 UTC
Labels: enhancement

**Comment by nemethviktor** [comment] 2022-12-22 12:28
Re: editing/deleting Favourites -> One for next year ;)

**Comment by nemethviktor** [comment] 2023-01-04 15:34
Ok added a logic to do a Manage Favourites, can you check the usual link pls -> https://drive.google.com/file/d/18iI77SIdrIv-joOtyT0-MzqOVtB5OgM0/view?usp=share_link

@aphalo

**Comment by aphalo** [comment] 2023-01-05 11:26
@nemethviktor Thanks!
The new dialogue seems to work as expected. On the other hand I cannot apply a favourite to images or save a new favourite. I get an "Unhandled exception". I copy the exception message below (from trying to apply a favourite).

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Column 'favouriteName' does not belong to table Favourites.
   at System.Data.DataRow.GetDataColumn(String columnName)
   at System.Data.DataRow.get_Item(String columnName)
   at System.Data.DataRowExtensions.Field[T](DataRow row, String columnName)
   at GeoTagNinja.FrmMainApp.<>c__DisplayClass97_0.<btn_LoadFavourite_Click>b__0(DataRow dataRow)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at GeoTagNinja.FrmMainApp.<btn_LoadFavourite_Click>d__97.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
GeoTagNinja
    Assembly Version: 0.7.8405.16774
    Win32 Version: 0.7.8405.16774
    CodeBase: file:///C:/Program%20Files/GeoTagNinja/GeoTagNinja.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4550.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4536.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
NLog
    Assembly Version: 5.0.0.0
    Win32 Version: 5.1.0.1480
    CodeBase: file:///C:/Program%20Files/GeoTagNinja/NLog.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4590.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4584.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Data.SQLite
    Assembly Version: 1.0.117.0
    Win32 Version: 1.0.117.0
    CodeBase: file:///C:/Program%20Files/GeoTagNinja/System.Data.SQLite.DLL
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.2.27524
    CodeBase: file:///C:/Program%20Files/GeoTagNinja/Newtonsoft.Json.DLL
----------------------------------------
Microsoft.Web.WebView2.Core
    Assembly Version: 1.0.1462.37
    Win32 Version: 1.0.1462.37
    CodeBase: file:///C:/Program%20Files/GeoTagNinja/Microsoft.Web.WebView2.Core.DLL
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
System.Data.DataSetExtensions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.DataSetExtensions/v4.0_4.0.0.0__b77a5c561934e089/System.Data.DataSetExtensions.dll
----------------------------------------
CsvHelper
    Assembly Version: 30.0.0.0
    Win32 Version: 30.0.1.0
    CodeBase: file:///C:/Program%20Files/GeoTagNinja/CsvHelper.DLL
----------------------------------------
Microsoft.Bcl.AsyncInterfaces
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.51805
    CodeBase: file:///C:/Program%20Files/GeoTagNinja/Microsoft.Bcl.AsyncInterfaces.DLL
----------------------------------------
Microsoft.Web.WebView2.WinForms
    Assembly Version: 1.0.1462.37
    Win32 Version: 1.0.1462.37
    CodeBase: file:///C:/Program%20Files/GeoTagNinja/Microsoft.Web.WebView2.WinForms.DLL
----------------------------------------
RestSharp
    Assembly Version: 108.0.3.0
    Win32 Version: 108.0.3
    CodeBase: file:///C:/Program%20Files/GeoTagNinja/RestSharp.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
System.Threading.Tasks.Extensions
    Assembly Version: 4.2.0.1
    Win32 Version: 4.6.28619.01
    CodeBase: file:///C:/Program%20Files/GeoTagNinja/System.Threading.Tasks.Extensions.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
System.Text.Json
    Assembly Version: 7.0.0.1
    Win32 Version: 7.0.122.56804
    CodeBase: file:///C:/Program%20Files/GeoTagNinja/System.Text.Json.DLL
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.21.52210
    CodeBase: file:///C:/Program%20Files/GeoTagNinja/System.Runtime.CompilerServices.Unsafe.DLL
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4494.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.ValueTuple
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ValueTuple/v4.0_4.0.0.0__cc7b13ffcd2ddd51/System.ValueTuple.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4536.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by nemethviktor** [comment] 2023-01-05 11:51
Yeah that's a bit of my f...kup.
When I started coding that particular feature I called the column in SQLite `locationName` and then as time went on I think I did a mass replace to `favouriteName` -- ofc the problem is that the few users that downloaded whichever development version may have the old stuff in it. 
I'll come up with a way around it, apologies.

**Comment by aphalo** [comment] 2023-01-05 23:14
Problem solved. Thanks! (I am happy to reset the stored data if that helps.)
