### ISSUE TITLE
Map doesn't show up, and ''Get From Web' doesn't work

### ISSUE THREAD

**Issue by smfontes** [nemethviktor/GeoTagNinja#21] opened 2022-11-28 21:38 UTC
Hi,
I set up the two accounts needed (API key and user password). searching for "Chrüzegg" returned valid json. When I select a picture with coordinates, no map appears. Also, when I use 'Get From Web' it pops up a window that has 'Info' as the title, an 'i' in a circle for content, and an OK button. No information is filled in.
I'd really love to get this working.

**Comment by nemethviktor** [comment] 2022-11-28 23:25
Hey, what windows version and language are you using?
Any chance you can share an image that does not work? (The actual photo that is, not a screenshot)

Thanks

V.

**Comment by Urmel** [comment] 2022-11-30 19:59
Hi @smfontes,

any chance we get the more detailed info on the issue so that we can look for the cause?

**Starting with "no map appears"**
... a couple of questions
- does this happen for every image or just one (or a set of) image(s)?
- is the webview runtime installed? Like this:
![grafik](https://user-images.githubusercontent.com/1786902/204895874-73155aff-fe7c-4cb1-a5c3-273153b5900e.png)
- when you do a fresh start of the application and the directly navigate to the affected image - does it still happen?
- which version of the GeoTagNinja did you use - the official release or one of the current builds from the other issue? you can find the version under menu "Help" --> "About".

And could we then get
- a screenshot of the application with missing map
- version info on the webview runtime (see above)

Thanks!
BR
Alex

**Comment by Urmel** [comment] 2022-12-12 22:04
Hi @smfontes,

any more words on this? I cannot reproduce it...

Otherwise, I suggest to close the issue as stalled...

Thanks!
BR
Alex

**Comment by nemethviktor** [comment] 2022-12-18 09:09
Closing as user has gone quiet - reopen if needed.

**Closed by nemethviktor** 2022-12-18 09:09 UTC
